# config.yaml
n_epochs: 1000
l_r: 20
l_i: 20
l_t: 2.5
l_gp: 5
device: 'cuda'
alpha: 1.5
batch_size: 256
learningrate: 0.0001
betas: [0.5, 0.999]
celeba: '../celeba'
fft_model_save_dir: './fftmodelsaves'
fft_generated_dir: './fftgenerated'
model_save_dir: './modelsaves'
generated_dir: './generated'
fft: True
train: False
sample: True
fid: False
no_of_samples: 5
checkpoint: '/home/rameshbabu/saves/model_epoch_1000_fft_sn.pt'
sampledir: './samples'
degrade: True
degradedir: './improved'
gen_dir: './generatedforfid'
real_dir: './realforfid'
samples_for_fid: 10000
spectralnorm: True